// AI NatSpec generator (mock implementation for local/dev usage)
// Provides simple line-based NatSpec/Doc generation for Solidity and Anchor Rust.

export type NatSpecDoc = {
  line: number;
  comment: string;
};

// Helpers
function extractParamsFromSolidity(line: string): string[] {
  const m = line.match(/\(([^)]*)\)/);
  const params: string[] = [];
  if (!m) return params;
  const inside = m[1].trim();
  if (!inside) return params;
  inside.split(',').forEach(p => {
    const t = p.trim();
    if (!t) return;
    const parts = t.split(/\s+/);
    const name = parts[parts.length - 1].replace(/\[.*\]/, '');
    params.push(name || t);
  });
  return params;
}

function extractReturnFromSolidity(line: string): boolean {
  return /returns\s*\(/i.test(line) || /returns\s*\(/i.test(line);
}

function extractParamsFromRust(line: string): string[] {
  const m = line.match(/\(([^)]*)\)/);
  const params: string[] = [];
  if (!m) return params;
  const inside = m[1].trim();
  if (!inside) return params;
  inside.split(',').forEach(p => {
    const t = p.trim();
    if (!t) return;
    const parts = t.split(':');
    const name = (parts[0] || '').trim();
    if (name) params.push(name);
  });
  return params;
}

export function generateSolidityDocs(content: string): NatSpecDoc[] {
  const docs: NatSpecDoc[] = [];
  const lines = content.split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const m = line.match(/function\s+([a-zA-Z_$][\w$]*)\s*\(/);
    if (m) {
      const name = m[1];
      const lineNum = i + 1;
      // Title and meta
      docs.push({ line: lineNum, comment: `/// @title ${name}` });
      docs.push({ line: lineNum, comment: `/// @author AutoGenerated` });
      docs.push({ line: lineNum, comment: `/// @notice Auto-generated documentation for ${name}` });
      docs.push({ line: lineNum, comment: `/// @dev Auto-generated` });
      // Params
      const params = extractParamsFromSolidity(line);
      params.forEach(p => {
        docs.push({ line: lineNum, comment: `/// @param ${p} Auto-generated` });
      });
      // Return
      if (extractReturnFromSolidity(line)) {
        docs.push({ line: lineNum, comment: `/// @return Auto-generated` });
      }
    }
  }
  return docs;
}

export function generateRustDocs(content: string): NatSpecDoc[] {
  const docs: NatSpecDoc[] = [];
  const lines = content.split(/\r?\n/);
  // Module-level doc
  docs.push({ line: 1, comment: `/// Auto-generated documentation for Anchor program` });
  let inStruct = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Instruction handler typically as `fn name(`
    const m = line.match(/fn\s+([a-zA-Z_$][\w$]*)\s*\(/);
    if (m) {
      const name = m[1];
      const lineNum = i + 1;
      docs.push({ line: lineNum, comment: `/// Instruction: ${name} - autogenerated` });
      const params = extractParamsFromRust(line);
      params.forEach(p => {
        docs.push({ line: lineNum, comment: `/// @param ${p} Auto-generated` });
      });
      continue;
    }
    // Track struct fields
    const structMatch = line.match(/struct\s+([A-Za-z_$][\w$]*)\s*{/);
    if (structMatch) {
      inStruct = true;
      continue;
    }
    if (inStruct) {
      if (line.includes('}')) {
        inStruct = false;
        continue;
      }
      const fieldMatch = line.match(/\s*([A-Za-z_$][\w$]*)\s*:\s*[^,]+,?/);
      if (fieldMatch) {
        const fname = fieldMatch[1];
        const lineNum = i + 1;
        docs.push({ line: lineNum, comment: `/// Field: ${fname} - autogenerated` });
      }
    }
  }
  return docs;
}
