// Lightweight Auto-Repair v2 scaffold
// Reads synthetic build/test/audit reports and emits simple patch files
// Exposed as CommonJS module for test integration
"use strict";
const fs = require('fs');
const path = require('path');

function ensureDir(p) {
  if (!fs.existsSync(p)) {
    fs.mkdirSync(p, { recursive: true });
  }
}

/**
 * Run auto-repair against a given workspace directory.
 * It looks for:
 *  - reports/test.*.json containing failed test info
 *  - reports/audit.*.json containing critical/high findings
 * It creates simple patch files under patches/ for each finding.
 * Returns a summary object.
 */
function runAutoRepair(workspaceDir) {
  const reportsDir = path.resolve(workspaceDir, 'reports');
  const patchesDir = path.resolve(workspaceDir, 'patches');
  const summary = {
    testsRepaired: 0,
    auditsRepaired: 0,
    patches: []
  };

  if (!fs.existsSync(reportsDir)) {
    return { ok: true, summary: 'No reports found' };
  }

  ensureDir(patchesDir);

  // Collect test reports
  const testFiles = fs.readdirSync(reportsDir).filter(n => /^test\..*\.json$/.test(n));
  testFiles.forEach((fname) => {
    const fpath = path.resolve(reportsDir, fname);
    let data;
    try {
      data = JSON.parse(fs.readFileSync(fpath, 'utf8'));
    } catch (e) {
      // skip invalid files
      return;
    }
    if (data && Array.isArray(data.tests)) {
      data.tests.forEach(t => {
        if (t && t.error) {
          const patchName = `patch-test-${path.basename(fname, '.json')}-${Date.now()}.txt`;
          const patchPath = path.resolve(patchesDir, patchName);
          const content = `# Auto-Repair Patch for test: ${t.name || 'unknown'}\n# reason: ${t.error}\n# generated by AutoRepair v2`;
          fs.writeFileSync(patchPath, content);
          // placeholder: repaired count tracked via summary.testsRepaired
          summary.patches.push(patchPath);
          // increment in a simple way
          summary.testsRepaired = (summary.testsRepaired || 0) + 1;
        }
      });
    }
  });

  // Collect audit reports
  const auditFiles = fs.readdirSync(reportsDir).filter(n => /^audit\..*\.json$/.test(n));
  auditFiles.forEach((fname) => {
    const fpath = path.resolve(reportsDir, fname);
    let data;
    try {
      data = JSON.parse(fs.readFileSync(fpath, 'utf8'));
    } catch (e) {
      return;
    }
    if (data && Array.isArray(data.findings)) {
      data.findings.forEach(f => {
        if (f && (f.type === 'Critical' || f.type === 'High')) {
          const patchName = `patch-audit-${path.basename(fname, '.json')}-${Date.now()}.txt`;
          const patchPath = path.resolve(patchesDir, patchName);
          const content = `# Auto-Repair Patch for audit: ${f.title || f.description || 'audit'}\n# type: ${f.type}\n# location: ${f.location || 'unknown'}\n# generated by AutoRepair v2`;
          fs.writeFileSync(patchPath, content);
          summary.patches.push(patchPath);
          summary.auditsRepaired = (summary.auditsRepaired || 0) + 1;
        }
      });
    }
  });

  // simple indicator log
  summary.patches = Array.from(new Set(summary.patches));
  summary.ok = true;

  // Persist a lightweight progress snapshot to help retries (progress.txt)
  try {
    const progressPath = path.resolve(workspaceDir, 'progress.txt');
    const progressLine = `testsRepaired=${summary.testsRepaired || 0};auditsRepaired=${summary.auditsRepaired || 0};patches=${summary.patches.length}`;
    fs.writeFileSync(progressPath, progressLine + '\n', 'utf8');
  } catch (e) {
    // non-fatal; ignore progress file issues
  }
  return { ok: true, summary };
}

module.exports = {
  runAutoRepair
};
