// Lightweight JS wrapper for AI-driven cross-chain migration wizard
// Exposes analyzeContract for runtime tests without TS tooling

function analyzeContract(sourceCode, sourceChain, targetChain) {
  const notes = [];
  const generatedSnippets = [];
  const issues = [];

  if (typeof sourceCode === 'string') {
    if (sourceCode.includes('mapping(')) {
      notes.push('Detected Solidity mapping; will map to PDA on target chain');
    }
    if (sourceCode.includes('struct ')) {
      notes.push('Detected Solidity struct; will map to Account on target chain');
    }
  }

  generatedSnippets.push(`// Migration stub from ${sourceChain} to ${targetChain}`);
  const canAutoTranslate = true;
  if (typeof sourceCode === 'string' && sourceCode.includes('require(')) {
    issues.push('Requires conversion of require to assertion with error codes');
  }

  return {
    sourceChain,
    targetChain,
    notes,
    generatedSnippets,
    canAutoTranslate,
    issues,
  };
}

// Export additional utility to generate a target code skeleton from a plan
function generateTargetCode(plan) {
  if (!plan) return '';
  const header = `// Auto-generated target code: ${plan.sourceChain} → ${plan.targetChain}\n`;
  const notes = Array.isArray(plan.notes) && plan.notes.length
    ? plan.notes.map(n => `// ${n}`).join('\n') + '\n'
    : '';
  const snippets = Array.isArray(plan.generatedSnippets) && plan.generatedSnippets.length
    ? plan.generatedSnippets.join('\n') + '\n'
    : '';
  const body = `// NOTE: This is a placeholder generated by AI migration tooling.\n`;
  return header + notes + snippets + body;
}

module.exports = { analyzeContract, generateTargetCode };
