// S39 Cross-Chain Migration Wizard (JavaScript version)
// Lightweight DOM-based module for a minimal AI-assisted cross-chain migration UI.

function createElement(tag, attrs, text) {
  const el = document.createElement(tag);
  if (attrs) {
    Object.keys(attrs).forEach((k) => el.setAttribute(k, attrs[k]));
  }
  if (text !== undefined) el.textContent = text;
  return el;
}

const SOURCE_OPTIONS = ['Solidity (EVM)', 'Rust/Anchor (SVM)', 'Move (SVM)'];
const TARGET_OPTIONS = ['Rust/Anchor (SVM)', 'Solidity (EVM)', 'Move (SVM)'];

function createMigrationWizard(container, opts) {
  const state = {
    source: opts?.sourceLabel ?? SOURCE_OPTIONS[0],
    target: opts?.targetLabel ?? TARGET_OPTIONS[0],
    contractCode: '',
    generatedCode: '',
    step: 'idle',
  };

  const wrapper = createElement('div', { class: 's39-migration' });
  wrapper.appendChild(createElement('h2', {}, 'AI-assisted Cross-Chain Migration'));

  const srcLabel = createElement('label', {}, 'Source:');
  const srcSel = createElement('select');
  SOURCE_OPTIONS.forEach((opt) => {
    const o = createElement('option', { value: opt }, opt);
    if (opt === state.source) o.selected = true;
    srcSel.appendChild(o);
  });
  srcSel.addEventListener('change', () => {
    state.source = srcSel.value || SOURCE_OPTIONS[0];
  });
  wrapper.appendChild(srcLabel);
  wrapper.appendChild(srcSel);

  wrapper.appendChild(createElement('br'));

  const tgtLabel = createElement('label', {}, 'Target:');
  const tgtSel = createElement('select');
  TARGET_OPTIONS.forEach((opt) => {
    const o = createElement('option', { value: opt }, opt);
    if (opt === state.target) o.selected = true;
    tgtSel.appendChild(o);
  });
  tgtSel.addEventListener('change', () => {
    state.target = tgtSel.value || TARGET_OPTIONS[0];
  });
  wrapper.appendChild(tgtLabel);
  wrapper.appendChild(tgtSel);

  wrapper.appendChild(createElement('hr'));

  const contractLabel = createElement('label', {}, 'Contract code (paste):');
  const contractArea = /** @type {HTMLTextAreaElement} */ (createElement('textarea', { rows: '8', cols: '60', placeholder: 'Paste source contract here...' }));
  contractArea.addEventListener('input', () => {
    state.contractCode = contractArea.value;
  });
  wrapper.appendChild(contractLabel);
  wrapper.appendChild(createElement('br'));
  wrapper.appendChild(contractArea);

  wrapper.appendChild(createElement('hr'));

  const btn = createElement('button', { type: 'button' }, 'Analyze & Generate Target Code');
  btn.addEventListener('click', async () => {
    state.step = 'analyzing';
    await new Promise((r) => setTimeout(r, 250));
    const headerName = String(state.source);
    const targetName = String(state.target);
    state.generatedCode = `// Generated target code (mock)\n// Source: ${headerName}\n// Target: ${targetName}\n\n// NOTE: This is a placeholder generated by the migration wizard.\n`;
    state.step = 'generated';
    if (preBlock) preBlock.textContent = state.generatedCode;
  });
  wrapper.appendChild(btn);

  const preBlock = createElement('pre');
  preBlock.style.background = '#111';
  preBlock.style.color = '#ddd';
  preBlock.style.padding = '12px';
  preBlock.style.border = '1px solid #333';
  preBlock.style.marginTop = '8px';
  preBlock.textContent = state.generatedCode || '// Generated code will appear here...';
  wrapper.appendChild(preBlock);

  container.appendChild(wrapper);
  return state;
}

export { createMigrationWizard };
export default createMigrationWizard;
