// S39 Cross-Chain Migration Wizard (TypeScript)
// Lightweight UI logic to scaffold AI-assisted chain migrations (EVM <-> SVM <-> Move).
// This module intentionally avoids framework dependencies and works with plain DOM.

export interface MigrationOptions {
  sourceLabel?: string;
  targetLabel?: string;
  contractName?: string;
}

export type MigrationStep = 'idle' | 'analyzing' | 'generated' | 'error';

export interface MigrationState {
  source: string; // e.g. 'Solidity (EVM)'
  target: string; // e.g. 'Rust/Anchor (SVM)'
  contractCode: string;
  generatedCode: string;
  step: MigrationStep;
  report?: string;
}

// Minimal set of source/target options
const SOURCE_OPTIONS = [
  'Solidity (EVM)',
  'Rust/Anchor (SVM)',
  'Move (SVM)' // for SVM->Move migrations targeting Sui/Aptos
];

const TARGET_OPTIONS = [
  'Rust/Anchor (SVM)',
  'Solidity (EVM)',
  'Move (SVM)'
];

function createElement<K extends keyof HTMLElementTagNameMap>(tag: K, attrs?: {[key: string]: string}, text?: string): HTMLElementTagNameMap[K] {
  const el = document.createElement(tag);
  if (attrs) {
    for (const k of Object.keys(attrs)) {
      el.setAttribute(k, attrs[k]);
    }
  }
  if (text !== undefined) el.textContent = text;
  return el;
}

export function createMigrationWizard(container: HTMLElement, opts?: MigrationOptions): MigrationState {
  // basic internal state
  const state: MigrationState = {
    source: (opts?.sourceLabel ?? SOURCE_OPTIONS[0]),
    target: (opts?.targetLabel ?? TARGET_OPTIONS[0]),
    contractCode: '',
    generatedCode: '',
    step: 'idle',
    report: undefined
  };

  // Build UI
  const wrapper = createElement('div', { class: 's39-migration' });

  const header = createElement('h2', {}, 'AI-assisted Cross-Chain Migration');
  wrapper.appendChild(header);

  // Source selector
  const srcLabel = createElement('label', {}, 'Source:');
  const srcSel = createElement('select');
  SOURCE_OPTIONS.forEach((opt) => {
    const o = createElement('option', { value: opt }, opt);
    if (opt === state.source) o.selected = true;
    srcSel.appendChild(o);
  });
  srcSel.addEventListener('change', () => {
    state.source = (srcSel.value || SOURCE_OPTIONS[0]);
  });
  wrapper.appendChild(srcLabel);
  wrapper.appendChild(srcSel);

  wrapper.appendChild(createElement('br'));

  // Target selector
  const tgtLabel = createElement('label', {}, 'Target:');
  const tgtSel = createElement('select');
  TARGET_OPTIONS.forEach((opt) => {
    const o = createElement('option', { value: opt }, opt);
    if (opt === state.target) o.selected = true;
    tgtSel.appendChild(o);
  });
  tgtSel.addEventListener('change', () => {
    state.target = (tgtSel.value || TARGET_OPTIONS[0]);
  });
  wrapper.appendChild(tgtLabel);
  wrapper.appendChild(tgtSel);

  wrapper.appendChild(createElement('hr'));

  // Contract input
  const contractLabel = createElement('label', {}, 'Contract code (paste):');
  const contractArea = createElement('textarea', {
    rows: '8',
    cols: '60',
    placeholder: 'Paste source contract here...'
  }) as HTMLTextAreaElement;
  contractArea.addEventListener('input', () => {
    state.contractCode = contractArea.value;
  });
  wrapper.appendChild(contractLabel);
  wrapper.appendChild(createElement('br'));
  wrapper.appendChild(contractArea);

  wrapper.appendChild(createElement('hr'));

  // Action button
  const btn = createElement('button', { type: 'button' }, 'Analyze & Generate Target Code');
  btn.addEventListener('click', async () => {
    // simple, idempotent mock analysis
    state.step = 'analyzing';
    // simulate delay
    await new Promise((r) => setTimeout(r, 250));
    // naive code generation placeholder
    const headerName = (state.source || '').toString();
    const targetName = (state.target || '').toString();
    const codeSample = `// Generated target code (mock)\n// Source: ${headerName}\n// Target: ${targetName}\n\n// NOTE: This is a placeholder generated by the migration wizard.\n`+
      `// In a real scenario, this would be translated by AI and validated by tests.\n`;
    state.generatedCode = codeSample;
    state.step = 'generated';
    preBlock.textContent = state.generatedCode;
  });
  wrapper.appendChild(btn);

  // Output area for generated code
  const preBlock = createElement('pre') as HTMLElement;
  preBlock.style.background = '#111';
  preBlock.style.color = '#ddd';
  preBlock.style.padding = '12px';
  preBlock.style.border = '1px solid #333';
  preBlock.style.marginTop = '8px';
  preBlock.textContent = state.generatedCode || '// Generated code will appear here...';
  wrapper.appendChild(preBlock);

  // Attach to container
  container.appendChild(wrapper);

  // expose a tiny API to read report
  (wrapper as any).getMigrationState = () => ({ ...state });
  return state;
}

export default createMigrationWizard;
